<?php
declare(strict_types=1);

return [
    'jpg'     => true,
    'png'     => true,
    'gif'     => true,
    'jpeg'    => true,
    'bmp'     => true,
    'mpeg'    => true,
    'mp4'     => true,
    'flv'     => true,
    'avi'     => true,
    'mkv'     => true,
    'mp3'     => true,
    'wma'     => true,
    'doc'     => true,
    'docx'    => true,
    'zip'     => true,
    'gz'      => true,
    'gzip'    => true,
    'pdf'     => true,
    'torrent' => true,
    'xls'     => true,
    'xlsx'    => true,
    'ppt'     => true,
    'pptx'    => true,
    'txt'     => true,
    'wmv'     => true,
    'djvu'    => true,
];
